server:
  port: 8082

spring:
  datasource:
    driver-class-name:
    url: jdbc:mysql://localhost:3306/my_test?characterEncoding=utf8&useConfigs=maxPerformance&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: 123456


  jpa:
    show-sql: false

  data:
    elasticsearch:
      repositories:
        enabled: true





